manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/bigtree908
  projects:
    - name: zmk
      remote: bigtree908
      revision: mouse
      import: app/west.yml
  self:
    path: config
