manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/bigtree908
    - name: nrf
      url-base: https://github.com/nrfconnect
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: points-move-scroll
      import: app/west.yml
    - name: sdk-nrf
      remote: nrf
      revision: v2.5-branch
      path: this/that
  self:
    path: config
