manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/amkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: pr/2027
      import: app/west.yml
  self:
    path: config
