file_format: "1"
id: puffin
name: puffin
url: https://lowprokb.ca/collections/keyboards/products/corne-ish-zen
type: board
arch: arm
features:
  - keys
outputs:
  - usb
  - ble
siblings:
  - puffin_left
  - puffin_right
